### ISSUE TITLE
Gettis this error spammed in my logs

### ISSUE THREAD

**Issue by laggis** [CIDR-Blocker/CIDR-Blocker#1]
CIDR_Blocker.smx] Failed to fetch CIDR: BIGINT UNSIGNED value is out of range in '((0x01 << (32 - substring_index(`fpsgaming_vpn`.`cidr_list`.`cidr`,'/',<cache>(-(1))))) - 1)'

how can i fix that?

**Comment by rumblefrog** [comment]
Could you provide the database version, and potentially the client's IP that triggering this?

**Comment by laggis** [comment]
The error is coming up when i start the server just the bot that have join the server and im using phpmyadmin version 4.7.7 and mysql - 5.1.73

**Comment by rumblefrog** [comment]
I have released v1.1.5, could you check if that works.

**Comment by laggis** [comment]
The error have stop spamming now seems like that fix the problem will give you more update later 


update no more error so the problem is fixed
