### ISSUE TITLE
Translation file

### ISSUE THREAD

**Issue by kilroy98** [CIDR-Blocker/CIDR-Blocker#3]
Please add translation file support, for translation plugin to other languages

**Comment by rumblefrog** [comment]
Which portion needs translating?

**Comment by kilroy98** [comment]
Maybe log's, kick reason.

**Comment by kilroy98** [comment]
Maybe log's, kick reason.

**Comment by rumblefrog** [comment]
That's what kick_message is for

`kick_message - Message to display when kicked`
